# Generated by Django 4.2.5 on 2023-10-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videolessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='last_watched_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
