# Generated by Django 4.2.5 on 2023-10-02 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videolessons', '0002_lessonprogress_last_watched_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='last_watched_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='productaccess',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='videolessons.product'),
        ),
    ]
